### ISSUE TITLE
Diagram not shown if used in statement

### ISSUE THREAD

**Issue by felixlen** [numbas/numbas-extension-jsxgraph#3]
If a JSXGraph diagram is used in the statement of a question, it is not shown when rendering (clicking on Run in the editor). However, using the preview functionality in the editor shows the diagram.
I currently use as simple workaround an Information statement part which fully does the trick for me. Nevertheless I wanted to report the issue as potential bug, but given the easy workaround I do not think that this a big issue also in the current state.

**Comment by christianp** [comment]
This would be a bug, but I can't reproduce it. Can you give me a link to a question where there's supposed to be a diagram in the statement, and it doesn't show up?

**Comment by felixlen** [comment]
Thanks for looking into it. https://numbas.mathcentre.ac.uk/question/133971/koordinaten-aus-zeichnung-ablesen/ (I have given access to your user and will publish it once it is final).

**Comment by christianp** [comment]
Thanks.
The problem is that you've used it in both the Statement and the Advice. An HTML element can only be in one place, so it ends up in the one that comes last, the Advice section. 

The editor should show you a warning about this, but maybe it's not triggered because the variable has the type `jsxgraph` instead of `html`. I'll look into it.

**Comment by felixlen** [comment]
Good to know, thanks!
